In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"C:\Users\parma\Downloads\ICU_DATASET.csv")
df.head()

,patient_id,age,gender,admission_type,comorbidity_score,heart_rate_mean,heart_rate_std,heart_rate_max,heart_rate_min,systolic_bp_mean,...,glucose_mean,lactate_mean,urine_output_total,ventilation_required,vasopressor_used,length_of_stay_days,apache_score,sofa_score,sepsis_flag,mortality_label
0,PAT000001,32,Male,Urgent,3.75,136.06,19.64,162.01,127.16,104.04,...,73.71,7.77,4245.99,0,0,6.32,15.65,10.50,0,0
1,PAT000002,46,Male,Urgent,2.91,108.95,7.79,124.18,94.79,131.05,...,78.36,5.06,1267.36,0,1,29.00,33.29,6.09,0,1
2,PAT000003,87,Male,Urgent,6.84,95.21,7.44,117.54,89.35,171.84,...,168.41,1.89,4863.13,1,1,26.95,25.93,18.44,0,1
3,PAT000004,21,Male,Emergency,1.96,63.62,11.51,82.22,51.84,164.59,...,214.40,1.06,4940.99,1,0,1.16,33.54,14.14,0,1
4,PAT000005,21,Male,Urgent,7.71,65.92,12.17,74.98,39.34,146.10,...,201.33,5.28,4492.46,0,0,21.68,31.63,11.23,0,0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   patient_id             15000 non-null  str
 1   age                    15000 non-null  int64
 2   gender                 15000 non-null  str
 3   admission_type         15000 non-null  str
 4   comorbidity_score      15000 non-null  float64
 5   heart_rate_mean        15000 non-null  float64
 6   heart_rate_std         15000 non-null  float64
 7   heart_rate_max         15000 non-null  float64
 8   heart_rate_min         15000 non-null  float64
 9   systolic_bp_mean       15000 non-null  float64
 10  systolic_bp_std        15000 non-null  float64
 11  respiratory_rate_mean  15000 non-null  float64
 12  spo2_mean              15000 non-null  float64
 13  temperature_mean       15000 non-null  float64
 14  glucose_mean           15000 non-null  float64
 15  lactate_mean           15000 non-null  float64
 16  urine_output_total     15000 non-null  float64
 17  ventilation_required   15000 non-null  int64
 18  vasopressor_used       15000 non-null  int64
 19  length_of_stay_days    15000 non-null  float64
 20  apache_score           15000 non-null  float64
 21  sofa_score             15000 non-null  float64
 22  sepsis_flag            15000 non-null  int64
 23  mortality_label        15000 non-null  int64
dtypes: float64(16), int64(5), str(3)
memory usage: 2.7 MB

In [5]:
df.describe()

,age,comorbidity_score,heart_rate_mean,heart_rate_std,heart_rate_max,heart_rate_min,systolic_bp_mean,systolic_bp_std,respiratory_rate_mean,spo2_mean,...,glucose_mean,lactate_mean,urine_output_total,ventilation_required,vasopressor_used,length_of_stay_days,apache_score,sofa_score,sepsis_flag,mortality_label
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,...,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,53.987533,4.988851,100.026900,15.087800,122.477551,82.523059,134.780335,12.539299,23.612935,90.051769,...,159.115675,4.270719,2760.416425,0.302200,0.245133,15.432166,22.496783,9.982515,0.201933,0.227867
std,21.027881,2.896171,23.187937,5.780114,25.304740,24.393954,25.982344,4.327404,6.654296,5.750619,...,51.867736,2.154312,1297.457979,0.459227,0.430181,8.368326,10.087201,5.747374,0.401456,0.419470
min,18.000000,0.000000,60.000000,5.000000,65.260000,30.600000,90.010000,5.000000,12.000000,80.000000,...,70.010000,0.500000,500.030000,0.000000,0.000000,1.000000,5.000000,0.000000,0.000000,0.000000
25%,36.000000,2.420000,80.027500,10.077500,102.430000,62.207500,112.187500,8.780000,17.880000,85.080000,...,114.430000,2.420000,1636.355000,0.000000,0.000000,8.140000,13.640000,4.967500,0.000000,0.000000
50%,54.000000,4.980000,99.925000,15.180000,122.450000,82.575000,134.555000,12.570000,23.650000,90.020000,...,158.615000,4.290000,2767.555000,0.000000,0.000000,15.470000,22.635000,10.040000,0.000000,0.000000
75%,72.000000,7.540000,120.160000,20.080000,142.465000,102.842500,157.370000,16.260000,29.400000,95.000000,...,203.870000,6.120000,3887.780000,1.000000,0.000000,22.670000,31.140000,14.930000,0.000000,0.000000
max,90.000000,10.000000,140.000000,25.000000,179.320000,134.330000,180.000000,20.000000,35.000000,100.000000,...,249.980000,8.000000,4999.540000,1.000000,1.000000,30.000000,40.000000,20.000000,1.000000,1.000000

In [6]:
print(df.columns)

Index(['patient_id', 'age', 'gender', 'admission_type', 'comorbidity_score',
       'heart_rate_mean', 'heart_rate_std', 'heart_rate_max', 'heart_rate_min',
       'systolic_bp_mean', 'systolic_bp_std', 'respiratory_rate_mean',
       'spo2_mean', 'temperature_mean', 'glucose_mean', 'lactate_mean',
       'urine_output_total', 'ventilation_required', 'vasopressor_used',
       'length_of_stay_days', 'apache_score', 'sofa_score', 'sepsis_flag',
       'mortality_label'],
      dtype='str')

In [7]:
df.isnull().sum()

patient_id               0
age                      0
gender                   0
admission_type           0
comorbidity_score        0
heart_rate_mean          0
heart_rate_std           0
heart_rate_max           0
heart_rate_min           0
systolic_bp_mean         0
systolic_bp_std          0
respiratory_rate_mean    0
spo2_mean                0
temperature_mean         0
glucose_mean             0
lactate_mean             0
urine_output_total       0
ventilation_required     0
vasopressor_used         0
length_of_stay_days      0
apache_score             0
sofa_score               0
sepsis_flag              0
mortality_label          0
dtype: int64

In [8]:
X = df.drop("mortality_label", axis=1)
y = df["mortality_label"]

In [9]:
X = X.drop("patient_id", axis=1)

In [10]:
X = pd.get_dummies(X, drop_first=True)

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()

In [14]:
y_pred_lr = lr.predict(X_test)

In [15]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, roc_auc_score

print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print("Recall:", recall_score(y_test, y_pred_lr))
print("Precision:", precision_score(y_test, y_pred_lr))
print("AUC:", roc_auc_score(y_test, y_pred_lr))

Accuracy: 0.7683333333333333
Recall: 0.02844950213371266
Precision: 0.625
AUC: 0.5116126483241483

In [16]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [17]:
y_pred_rf = rf.predict(X_test)

In [18]:
print("RF Accuracy:", accuracy_score(y_test, y_pred_rf))
print("RF Recall:", recall_score(y_test, y_pred_rf))
print("RF Precision:", precision_score(y_test, y_pred_rf))
print("RF AUC:", roc_auc_score(y_test, y_pred_rf))

RF Accuracy: 0.7646666666666667
RF Recall: 0.002844950213371266
RF Precision: 0.2857142857142857
RF AUC: 0.5003340989638906

In [19]:
feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
}).sort_values(by="Importance", ascending=False)

feature_importance.head(10)

                  Feature  Importance
1       comorbidity_score    0.063872
17           apache_score    0.063286
18             sofa_score    0.059960
6        systolic_bp_mean    0.056647
12           lactate_mean    0.056471
11           glucose_mean    0.056230
13     urine_output_total    0.055489
8   respiratory_rate_mean    0.055343
3          heart_rate_std    0.054989
9               spo2_mean    0.054853

In [20]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred_rf)

array([[2292,    5],
       [ 701,    2]])

In [21]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.77      1.00      0.87      2297
           1       0.29      0.00      0.01       703

    accuracy                           0.76      3000
   macro avg       0.53      0.50      0.44      3000
weighted avg       0.65      0.76      0.66      3000

In [22]:
import joblib

joblib.dump(rf, "icu_model.pkl")

['icu_model.pkl']

In [23]:
import joblib

# Load model
model = joblib.load("icu_model.pkl")

print("Model loaded successfully")

Model loaded successfully

In [24]:
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]

print(y_pred[:5])
print(y_prob[:5])

[0 0 0 0 0]
[0.16 0.13 0.38 0.13 0.21]

In [25]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_prob)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("AUC:", auc)

Accuracy: 0.7646666666666667
Precision: 0.2857142857142857
Recall: 0.002844950213371266
AUC: 0.6086066246343954

In [26]:
import pandas as pd
import matplotlib.pyplot as plt

importance = model.feature_importances_
features = X.columns

feature_imp = pd.DataFrame({
    'Feature': features,
    'Importance': importance
}).sort_values(by="Importance", ascending=False)

print(feature_imp)

                     Feature  Importance
1          comorbidity_score    0.063872
17              apache_score    0.063286
18                sofa_score    0.059960
6           systolic_bp_mean    0.056647
12              lactate_mean    0.056471
11              glucose_mean    0.056230
13        urine_output_total    0.055489
8      respiratory_rate_mean    0.055343
3             heart_rate_std    0.054989
9                  spo2_mean    0.054853
16       length_of_stay_days    0.054252
10          temperature_mean    0.053106
7            systolic_bp_std    0.052385
4             heart_rate_max    0.051880
0                        age    0.051555
5             heart_rate_min    0.049810
2            heart_rate_mean    0.049398
15          vasopressor_used    0.013120
14      ventilation_required    0.013074
19               sepsis_flag    0.011093
20               gender_Male    0.008590
22     admission_type_Urgent    0.007355
21  admission_type_Emergency    0.007243

In [35]:
# Step 1: Import libraries
import pandas as pd
import joblib

# Step 2: Load dataset
df = pd.read_csv(r"C:\Users\parma\Downloads\ICU_DATASET.csv")

# Step 3: Select same features used during training
X = df.drop('mortality', axis=1)

# Step 4: Select one patient (change index if needed)
new_patient = X.sample(1)   # random patient

# Step 5: Load trained model
model = joblib.load("icu_model.pkl")

# Step 6: Predict
prediction = model.predict(new_patient)
probability = model.predict_proba(new_patient)[0][1]

# Step 7: Display patient data
print("===== Patient Data =====")
print(new_patient)

# Step 8: Display result
print("\n===== Prediction Result =====")
if prediction[0] == 1:
    print("⚠️ High Risk of Death")
else:
    print("✅ Low Risk (Survive)")

print("Risk Probability:", round(probability, 4))

KeyError: "['mortality'] not found in axis"

In [ ]:
def predict_patient(data):
    model = joblib.load("icu_model.pkl")
    pred = model.predict([data])[0]
    prob = model.predict_proba([data])[0][1]
    return pred, prob